printWidth: 120
tabWidth: 2
useTabs: false
semi: false
singleQuote: true
quoteProps: as-needed
jsxSingleQuote: true
trailingComma: es5
bracketSpacing: true
jsxBracketSameLine: true
arrowParens: always
parser: typescript
requirePragma: true
insertPragma: true
proseWrap: preserve
htmlWhitespaceSensitivity: strict
vueIndentScriptAndStyle: false
endOfLine: lf