sudo: false
language: node_js
node_js:
  - 10 # use nodejs v10 LTS
cache: npm
branches:
  only:
    - master # build master branch only
before_install:
  - cd ./docs
  - npm install -g hexo-cli
install:
  - npm install
script:
  - hexo clean
  - hexo generate # generate static files
deploy:
  provider: pages
  skip-cleanup: true
  github-token: ab75eee2725380595a3515d0f5e082a7d069489b
  keep-history: true
  on:
    branch: master
  local-dir: ./docs/public
